### ISSUE TITLE
User can browse the catalogs

### ISSUE THREAD

**Issue by alanho-05** [alanho-05/full-stack-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can browse the catalog of products

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be brought to the weapons catalog and will be able to switch to vehicle and throwable catalog.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="836" alt="Screenshot 2023-06-06 at 1 49 58 PM" src="https://github.com/alanho-05/full-stack-project/assets/23649469/e3b5c4f7-a1c4-4bb1-ad45-95579c1b6023">
<img width="1263" alt="Screenshot 2023-06-06 at 1 50 45 PM" src="https://github.com/alanho-05/full-stack-project/assets/23649469/f83c0ed8-53ca-4ea0-b774-76975c4e68e0">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a navbar component 
- [ ] Create a drawer component 
- [ ] Create a filter component
- [ ] Create product card component
- [ ] Create a footer component
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
